#wallpaper {
#  monitor = HDMI-A-1
#  path = ~/Pictures/wallpapers/long-street.jpg
#  fit_mode = cover
#}

#wallpaper {
#  monitor = HDMI-A-3
#  path = ~/Pictures/wallpapers/zoom.jpg
#  fit_mode = cover
#}

# Main 4k monitor
wallpaper {
  monitor = HDMI-A-1
  path = ~/Pictures/wallpapers/foggy-forest.jpg
  fit_mode = cover;
}

# Secondary monitor
wallpaper {
  monitor = HDMI-A-3
  path = ~/Pictures/wallpapers/foggy-forest.jpg
  fit_mode = cover;
}

# Thinkpad
wallpaper {
  monitor = eDP-1
  path = ~/Pictures/wallpapers/foggy_forest.jpg
  fit_mode = cover;
}
wallpaper {
  monitor = HDMI-A-3
  path = ~/Pictures/wallpapers/foggy_forest.jpg
  fit_mode = cover;
}
